### ISSUE TITLE
Method "pool_upgrade_request" has 11 parameters, which is greater than the 7 authorized.

### ISSUE THREAD

**Issue by JeromeK13** [swisscom-blockchain/sbca-indy-wrapper#11]
https://github.com/swisscom-blockchain/sbca-indy-wrapper/blob/49acc3a94d89af18692aac9dbe8586e5d0ab3728/sbca_wrapper/_commands/ledger.py#L111

(From Sonar-Cloud)

**Comment by JeromeK13** [comment]
I also would recommend pushing the code at some point to the Maser-Branche

**Comment by Skilletpan** [comment]
> I would also recommend pushing the code to the Master-Branch

Good job correcting your grammar ;)

**Comment by Skilletpan** [comment]
Can't resolve, as the function signature has to match the arguments of the Libindy command.
